
#> realistic_explosion:generated_summons/on_item
#
# @within			???
# @executed			as & at the item entity from the explosion
#
# @output storage	realistic_explosion:main Rotation : the rotation looking at the origin of the explosion
#
# @description		Calculate the length of the item name and execute the corresponding function
#
# @warning			This file is auto-generated by the generator.py script, do not edit it manually!
#

# Get the length of the item name
execute store result score #length realistic_explosion.data run data get entity @s Item.id

# Copy the item id to the storage
data modify storage realistic_explosion:main id set from entity @s Item.id

# Execute the function that will summon the falling block
execute if score #length realistic_explosion.data matches 13 run function realistic_explosion:generated_summons/13
execute if score #length realistic_explosion.data matches 14 run function realistic_explosion:generated_summons/14
execute if score #length realistic_explosion.data matches 15 run function realistic_explosion:generated_summons/15
execute if score #length realistic_explosion.data matches 16 run function realistic_explosion:generated_summons/16
execute if score #length realistic_explosion.data matches 17 run function realistic_explosion:generated_summons/17
execute if score #length realistic_explosion.data matches 18 run function realistic_explosion:generated_summons/18
execute if score #length realistic_explosion.data matches 19 run function realistic_explosion:generated_summons/19
execute if score #length realistic_explosion.data matches 20 run function realistic_explosion:generated_summons/20
execute if score #length realistic_explosion.data matches 21 run function realistic_explosion:generated_summons/21
execute if score #length realistic_explosion.data matches 22 run function realistic_explosion:generated_summons/22
execute if score #length realistic_explosion.data matches 23 run function realistic_explosion:generated_summons/23
execute if score #length realistic_explosion.data matches 24 run function realistic_explosion:generated_summons/24
execute if score #length realistic_explosion.data matches 25 run function realistic_explosion:generated_summons/25
execute if score #length realistic_explosion.data matches 26 run function realistic_explosion:generated_summons/26
execute if score #length realistic_explosion.data matches 27 run function realistic_explosion:generated_summons/27
execute if score #length realistic_explosion.data matches 28 run function realistic_explosion:generated_summons/28
execute if score #length realistic_explosion.data matches 29 run function realistic_explosion:generated_summons/29
execute if score #length realistic_explosion.data matches 30 run function realistic_explosion:generated_summons/30
execute if score #length realistic_explosion.data matches 31 run function realistic_explosion:generated_summons/31
execute if score #length realistic_explosion.data matches 32 run function realistic_explosion:generated_summons/32
execute if score #length realistic_explosion.data matches 33 run function realistic_explosion:generated_summons/33
execute if score #length realistic_explosion.data matches 34 run function realistic_explosion:generated_summons/34
execute if score #length realistic_explosion.data matches 35 run function realistic_explosion:generated_summons/35
execute if score #length realistic_explosion.data matches 36 run function realistic_explosion:generated_summons/36
execute if score #length realistic_explosion.data matches 37 run function realistic_explosion:generated_summons/37
execute if score #length realistic_explosion.data matches 38 run function realistic_explosion:generated_summons/38
execute if score #length realistic_explosion.data matches 39 run function realistic_explosion:generated_summons/39
execute if score #length realistic_explosion.data matches 40 run function realistic_explosion:generated_summons/40
execute if score #length realistic_explosion.data matches 41 run function realistic_explosion:generated_summons/41
execute if score #length realistic_explosion.data matches 42 run function realistic_explosion:generated_summons/42
execute if score #length realistic_explosion.data matches 43 run function realistic_explosion:generated_summons/43
execute if score #length realistic_explosion.data matches 44 run function realistic_explosion:generated_summons/44

# Get rotation looking at the origin of the explosion and kill the item entity
tp @s ~ ~ ~ facing entity @e[type=marker,tag=realistic_explosion.origin,limit=1] feet
data modify storage realistic_explosion:main Rotation set from entity @s Rotation
kill @s

# Execute the function as the new falling block
execute as @e[type=falling_block,tag=realistic_explosion.new] at @s run function realistic_explosion:falling_block/main

