
#> realistic_explosion:explode
#
# @within			Nothing, this function is manually called by the Library's User
# @executed			as unknown entity & at the explosion origin
#
# @description		Summons a temporary marker and execute the function that will handle the explosion
#
# @warning			This file is auto-generated by the generator script, do not edit it manually!
#

# Execute the function as the temporary marker
execute summon marker run function realistic_explosion:explosion/main

